const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Mock data
const data = {
  contract: {
    _id: 'sample-contract-id-123',
    createdAt: new Date(),
    wasteType: 'Recyclables (Paper/Plastic Mix)',
    monthlyQuantityKg: 5000,
    pricePerKg: 15,
    durationMonths: 12,
    customTerms: `1. Regular pickups every Tuesday and Friday.
2. Contamination levels must be below 5%.
3. Payment terms: Net 30 days.
4. Logistics handled by the receiver.
5. This is a very long line of custom terms to test how it wraps around the page boundaries. We want to see if it overflows the footer or the side margins when we don't have borders. 
6. Adding more content here: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
7. Even more content to trigger a second page: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
    buyerSignatureUrl: null,
    sellerSignatureUrl: null
  },
  proposer: {
    name: 'EcoCycle Corp',
    email: 'contact@ecocycle.com',
    role: 'company-seller'
  },
  receiver: {
    name: 'GreenRefine Ltd',
    email: 'procurement@greenrefine.com',
    role: 'company-buyer'
  }
};

const drawLongTermContract = async (doc, data) => {
  const { contract, proposer, receiver } = data;
  const PAGE_W = 612;
  const PAGE_H = 792;
  const MARGIN = 45;

  // ─── Colors ──────────────────────────────────────────────────
  const NAVY_DARK = '#020617';  // slate-950
  const NAVY_MID = '#0f172a';   // slate-900
  const NATURE_500 = '#22c55e'; // nature green
  const SLATE_400 = '#94a3b8';  // text-slate-400
  const SLATE_200 = '#e2e8f0';  // text-slate-200
  const BORDER_COLOR = '#1e293b'; // slate-800

  // ─── Background ───────────────────────────────────────────────
  doc.rect(0, 0, PAGE_W, PAGE_H).fill('#ffffff'); // White paper base

  // ─── Page Decoration Helpers ──────────────────────────────────
  const drawPageBorder = () => {
    doc.save();
    doc.rect(20, 20, PAGE_W - 40, PAGE_H - 40)
       .lineWidth(0.5)
       .strokeColor(BORDER_COLOR)
       .stroke();
    doc.restore();
  };

  const drawFooter = () => {
    doc.save();
    doc.rect(0, PAGE_H - 80, PAGE_W, 80).fill('#f8fafc');
    doc.fillColor(SLATE_400).fontSize(8).font('Helvetica')
      .text('This contract is a permanent digital record generated by the WasteWise Circular Economy Platform.', MARGIN, PAGE_H - 55, { align: 'center', width: PAGE_W - MARGIN * 2 });
    doc.fillColor(NATURE_500).fontSize(10).font('Helvetica-Bold')
      .text('WasteWise • Building a Greener Tomorrow', MARGIN, PAGE_H - 35, { align: 'center', width: PAGE_W - MARGIN * 2 });
    doc.restore();
  };

  // Initial decoration on first page
  drawPageBorder();
  drawFooter();

  // Set bottom margin to avoid collision with footer/border
  doc.page.margins.bottom = 100;

  // Handle new pages (borders + footer)
  doc.on('pageAdded', () => {
    doc.save();
    doc.rect(0, 0, PAGE_W, PAGE_H).fill('#ffffff');
    doc.restore();
    drawPageBorder();
    drawFooter();
    // Ensure new page also has the same bottom margin
    doc.page.margins.bottom = 100;
  });

  // ─── Header Section (Dark) ────────────────────────────────────
  // Drawn after border so it covers the top part of the border on page 1
  doc.rect(0, 0, PAGE_W, 160).fill(NAVY_DARK);
  
  // Decorative side bar
  doc.rect(0, 0, 8, 160).fill(NATURE_500);

  // Logo Placeholder / Brand
  doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold')
    .text('WasteWise', MARGIN, 40, { characterSpacing: 1 });
  doc.fillColor(NATURE_500).fontSize(8).font('Helvetica-Bold')
    .text('CIRCULAR ECONOMY NETWORK', MARGIN, 68, { characterSpacing: 2 });

  doc.fillColor('#ffffff').fontSize(18).font('Helvetica-Bold')
    .text('LONG-TERM WASTE SUPPLY CONTRACT', MARGIN, 100);
  
  doc.fillColor(SLATE_400).fontSize(9).font('Helvetica')
    .text(`CONTRACT REFERENCE: LTC-${contract._id.toString().toUpperCase()}`, MARGIN, 130);
  doc.text(`ISSUED ON: ${new Date(contract.createdAt).toLocaleDateString()}`, MARGIN, 142);

  let y = 190;

  // ─── 1. PARTIES ──────────────────────────────────────────────
  doc.fillColor(NAVY_MID).fontSize(14).font('Helvetica-Bold').text('1. CONTRACTING PARTIES', MARGIN, y);
  y += 25;
  doc.rect(MARGIN, y, PAGE_W - (MARGIN * 2), 1).fill(BORDER_COLOR);
  y += 20;

  const BOX_W = (PAGE_W - (MARGIN * 2) - 20) / 2;
  
  // Proposer Box
  doc.rect(MARGIN, y, BOX_W, 65).fill('#f8fafc');
  doc.rect(MARGIN, y, BOX_W, 65).lineWidth(0.5).stroke(BORDER_COLOR);
  doc.fillColor(SLATE_400).fontSize(8).font('Helvetica-Bold').text('PROPOSER (ISSUER)', MARGIN + 12, y + 10);
  doc.fillColor(NAVY_MID).fontSize(11).font('Helvetica-Bold').text(proposer.name, MARGIN + 12, y + 25);
  doc.fillColor(SLATE_400).fontSize(9).font('Helvetica').text(proposer.email, MARGIN + 12, y + 40);
  doc.text(`Role: ${proposer.role}`, MARGIN + 12, y + 52);

  // Receiver Box
  doc.rect(MARGIN + BOX_W + 20, y, BOX_W, 65).fill('#f8fafc');
  doc.rect(MARGIN + BOX_W + 20, y, BOX_W, 65).lineWidth(0.5).stroke(BORDER_COLOR);
  doc.fillColor(SLATE_400).fontSize(8).font('Helvetica-Bold').text('RECEIVER (COUNTERPARTY)', MARGIN + BOX_W + 32, y + 10);
  doc.fillColor(NAVY_MID).fontSize(11).font('Helvetica-Bold').text(receiver.name, MARGIN + BOX_W + 32, y + 25);
  doc.fillColor(SLATE_400).fontSize(9).font('Helvetica').text(receiver.email, MARGIN + BOX_W + 32, y + 40);
  doc.text(`Role: ${receiver.role}`, MARGIN + BOX_W + 32, y + 52);

  y += 100;

  // ─── 2. SUPPLY TERMS ─────────────────────────────────────────
  doc.fillColor(NAVY_MID).fontSize(14).font('Helvetica-Bold').text('2. TERMS OF SUPPLY', MARGIN, y);
  y += 25;
  doc.rect(MARGIN, y, PAGE_W - (MARGIN * 2), 1).fill(BORDER_COLOR);
  y += 20;

  const drawRow = (label, value, currentY) => {
    doc.fillColor(SLATE_400).fontSize(10).font('Helvetica-Bold').text(label, MARGIN + 10, currentY);
    doc.fillColor(NAVY_MID).fontSize(10).font('Helvetica').text(value, MARGIN + 220, currentY, { align: 'right', width: PAGE_W - MARGIN * 2 - 230 });
    doc.rect(MARGIN, currentY + 18, PAGE_W - MARGIN * 2, 0.5).fill('#f1f5f9');
    return currentY + 32;
  };

  y = drawRow('Material Specification', contract.wasteType, y);
  y = drawRow('Monthly Commitment', `${contract.monthlyQuantityKg.toLocaleString()} KG`, y);
  y = drawRow('Agreed Price per KG', `LKR ${contract.pricePerKg.toLocaleString()}`, y);
  y = drawRow('Agreement Duration', `${contract.durationMonths} Months`, y);
  y = drawRow('Total Contract Estimate', `LKR ${(contract.pricePerKg * contract.monthlyQuantityKg * contract.durationMonths).toLocaleString()}`, y);

  y += 20;

  // ─── 3. CUSTOM PROVISIONS ────────────────────────────────────
  if (contract.customTerms) {
    doc.fillColor(NAVY_MID).fontSize(14).font('Helvetica-Bold').text('3. CUSTOM PROVISIONS', MARGIN, y);
    y += 25;
    doc.rect(MARGIN, y, PAGE_W - (MARGIN * 2), 1).fill(BORDER_COLOR);
    y += 20;
    
    doc.fillColor(NAVY_MID).fontSize(10).font('Helvetica').text(contract.customTerms, MARGIN + 10, y, { 
      width: PAGE_W - (MARGIN * 2) - 30, // Slightly more padding
      lineGap: 4,
      align: 'justify'
    });
    
    // Calculate space taken by text
    const textHeight = doc.heightOfString(contract.customTerms, { 
      width: PAGE_W - (MARGIN * 2) - 30 
    });
    y += textHeight + 40;
  }

  // ─── 4. BINDING SIGNATURES ───────────────────────────────────
  if (y > PAGE_H - 250) {
    doc.addPage();
    y = 50;
  }

  doc.fillColor(NAVY_MID).fontSize(14).font('Helvetica-Bold').text('4. BINDING SIGNATURES', MARGIN, y);
  y += 25;
  doc.rect(MARGIN, y, PAGE_W - (MARGIN * 2), 1).fill(BORDER_COLOR);
  y += 30;

  const drawSig = async (label, url, startX, startY) => {
    doc.fillColor(SLATE_400).fontSize(9).font('Helvetica-Bold').text(label.toUpperCase(), startX, startY);
    doc.rect(startX, startY + 15, BOX_W, 100).fill('#fdfdfd');
    doc.rect(startX, startY + 15, BOX_W, 100).lineWidth(0.5).dash(4, { space: 2 }).stroke(BORDER_COLOR);
    doc.undash();
    doc.fillColor(SLATE_400).fontSize(8).text('Awaiting Signature', startX, startY + 55, { align: 'center', width: BOX_W });
    doc.fillColor(NAVY_MID).fontSize(8).font('Helvetica').text('Digitally Verified via WasteWise Auth', startX, startY + 120);
  };

  await drawSig('Buyer Signature', null, MARGIN, y);
  await drawSig('Seller Signature', null, MARGIN + BOX_W + 20, y);
};

async function generate() {
  const doc = new PDFDocument({ margin: 0, size: 'LETTER' });
  const outputPath = path.join(__dirname, 'test_contract.pdf');
  const writeStream = fs.createWriteStream(outputPath);
  doc.pipe(writeStream);

  await drawLongTermContract(doc, data);
  doc.end();

  writeStream.on('finish', () => {
    console.log(`Generated sample contract at: ${outputPath}`);
  });
}

generate();
